### ISSUE TITLE
telegram group chat open

### ISSUE THREAD

**Issue by iusamaashraf** [UsamaSarwar/flutter#3]
i am working on project where i need to open the community group of telegram as i work i can only open the individually chat but i need to open the community group how can i open that
can you please guide me 
Thanks in advance

**Comment by UsamaSarwar** [comment]
You may just open link to that group using url_launcher package.

**Comment by UsamaSarwar** [comment]
Hey @iusamaashraf,  

I’ve just added a method to open a Telegram community group directly. You can now use:  

```dart
Telegram.openChat(username: 'YourGroupUsername');
```  

Or, if you have an invite link, you can use:  

```dart
Telegram.joinChannel(inviteLink: 'https://t.me/joinchat/XXXXXXX');
```  

This will open the group in the Telegram app. Make sure to update to the latest version of the package to access this feature. Let me know if you need any further assistance!
